using System;
using System.Reflection;
using HarmonyLib;
using RimWorld.Planet;
using Verse;

namespace CelestialLighting.Probes;

// Excluded from the shipped CelestialLighting.dll (see the <Compile Remove> in
// CelestialLighting.csproj) and compiled into TestMod/CelestialLighting.Probes.csproj instead. This
// WRITES to another mod's state and must never reach a player's game; living under Probes/ is what
// guarantees that.
//
// Why it has to exist. Planetsmith's tilt is chosen in its world-generation UI and then frozen into
// the save, so a harness fixture can only ever carry ONE tilt — and the fixture we have
// (minimal_colony.rws) was generated before Planetsmith existed, which means its component is
// constructed at load from Planetsmith's mod-settings default of 23.4. That is 0.04 degrees from our
// own 23.44: a world where the interop is live and completely invisible, which is the one world a
// scenario cannot prove anything with.
//
// The alternative to this hook is a second fixture generated by hand through Planetsmith's world-gen
// UI at a steep tilt. That would test more (it would cover the generation path too) at the cost of a
// binary save nobody can review, regenerate, or diff — and it still could not A/B two tilts against
// the same world, because the tilt would be baked into the file.
//
// So: bridged as a harness feature flag rather than a step, because the FeatureRegistry bridge is
// already the dev-only escape hatch for exactly this shape of thing (the realistic_preset entry in
// ProbeRegistration writes mod settings the same way). Enabled writes SteepTiltDegrees, disabled puts
// back whatever the world had when we first touched it — so a scenario that flips it on and off
// again leaves the save as it found it, and the runner's between-scenario ResetAll() does too.
public static class PlanetsmithTiltOverride
{
    public const string FeatureKey = "planetsmith_steep_tilt";

    // 60 degrees, and specifically not 90. It has to be far enough from 23.44 that no tolerance can
    // absorb it — at 45 degrees latitude it moves midwinter noon from a sun 21.6 degrees up to one
    // 15 degrees BELOW the horizon, which is a polar night rather than a dimmer afternoon. 90 would
    // be a larger number and a worse test: it is the end of the slider, so a clamp bug that pinned
    // every tilt to the maximum would pass.
    public const float SteepTiltDegrees = 60f;

    private const string WorldComponentTypeName = "Planetsmith.PlanetsmithWorldComponent";
    private const string SettingsPropertyName = "Settings";
    private const string TiltFieldName = "axialTilt";

    private static bool overridden;
    private static float originalTilt;

    public static void Set(bool steep)
    {
        FieldInfo tilt = ResolveTiltField(out object settings);
        if (tilt == null)
            return;

        if (steep)
        {
            RememberOriginal(tilt, settings);
            tilt.SetValue(settings, SteepTiltDegrees);
            // Logged on SUCCESS, not only on failure. A test hook that silently does nothing is
            // indistinguishable from the feature under test not working, and telling those apart
            // from the report alone cost two live runs.
            Log.Message(
                $"[CelestialLighting.Probes] Planetsmith tilt override: {originalTilt} -> "
                + $"{tilt.GetValue(settings)} on settings#{settings.GetHashCode()}.");
            return;
        }

        // Restoring without having overridden would write a stale originalTilt over a world we never
        // touched — which, between scenarios in a suite, is exactly how one scenario's setup leaks
        // into the next one's world.
        if (!overridden)
            return;

        tilt.SetValue(settings, originalTilt);
        overridden = false;
    }

    // Captured on the first override only, so that flipping the flag on twice does not record 60 as
    // the "original" and make the restore a no-op.
    private static void RememberOriginal(FieldInfo tilt, object settings)
    {
        if (overridden)
            return;

        originalTilt = tilt.GetValue(settings) is float value ? value : 23.4f;
        overridden = true;
    }

    // Resolved fresh each call rather than cached: this runs a handful of times per scenario, and a
    // cache here would have to be invalidated on world reload — which is precisely the between-
    // scenario moment this hook must not get wrong.
    private static FieldInfo ResolveTiltField(out object settings)
    {
        settings = null;

        try
        {
            World world = Find.World;
            if (world == null)
                return Unresolved("there is no loaded world");

            Type componentType = AccessTools.TypeByName(WorldComponentTypeName);
            if (componentType == null)
                return Unresolved($"{WorldComponentTypeName} did not resolve");

            object component = FindComponent(world, componentType);
            if (component == null)
                return Unresolved("the loaded world carries no Planetsmith component");

            PropertyInfo settingsProperty = AccessTools.Property(componentType, SettingsPropertyName);
            if (settingsProperty == null)
                return Unresolved($"{SettingsPropertyName} did not resolve");

            settings = settingsProperty.GetValue(component);
            if (settings == null)
                return Unresolved($"{SettingsPropertyName} returned null");

            FieldInfo tilt = AccessTools.Field(settings.GetType(), TiltFieldName);
            return tilt ?? Unresolved($"{TiltFieldName} did not resolve on {settings.GetType().FullName}");
        }
        catch (Exception e)
        {
            Log.Warning($"[CelestialLighting.Probes] Could not reach Planetsmith's tilt: {e}");
            return null;
        }
    }

    // Every way this can decline to resolve says so. A silent null here does not fail the scenario —
    // the probe simply reads the tilt the world already had — which presents as an interop that did
    // not take effect rather than as a test hook that did not run. That distinction cost a live run
    // once already.
    private static FieldInfo Unresolved(string reason)
    {
        Log.Warning($"[CelestialLighting.Probes] Planetsmith tilt override did not apply: {reason}.");
        return null;
    }

    private static object FindComponent(World world, Type componentType)
    {
        foreach (WorldComponent component in world.components)
        {
            if (componentType.IsInstanceOfType(component))
                return component;
        }

        return null;
    }
}
